creation_rules:
  - path_regex: (secrets/.*\.yaml$|.*/secret(\.enc)?\.yaml$)
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
          - age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
