apiVersion: v1
kind: Secret
metadata:
    name: nextcrm-secrets
    namespace: ynoacamino
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:VdYUIcGskg==,iv:oeHkXuuu1SGV+XDrqB+Bk+GlpsSfimk8GhrEQ+HlYK0=,tag:TYlSHFUZJ8ur/hb7NncS6Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rJJE72cD+NM=,iv:XyGHqYHY0FRQNiAVzcSNfc5DvvTuskYhh77khlEis2I=,tag:PR63CkOFueQc9SgC1Ot9VA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:8Ntv3226SQ==,iv:zS1JsfnL6EoQJ2QAk9gp0SHuQ6KbtTFNOjeDadKQaAU=,tag:YIl9OjaydUSgmAyGohGVug==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:flXR9pZPwFkJ0lR+ZZNaLs1UnJbqHrae2Y0PGfwuzYrLBeiZenO80BxkfSzkINNt1qcV5yw=,iv:xicaZJeuvFypkQcnIvmjGz5OxZEAt9nGADwmcjDKQ/A=,tag:XTRzXVL5XcgSVTzTd/iXNw==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:B7MAOLrzcg==,iv:NiPmzPmivjZWNIOmkxGiFGzMT1oKr+PosFYmYVY3KGg=,tag:Ksdk6IPHZzai6p2Ba8ooZQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:exDieuIfJRo=,iv:D+4BwruETIZjGLTzgZLAD1Pl6WBFQvKcIZkbvvpUrh4=,tag:I4rwNHdLhQWRHwMOk7/lIQ==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:EaOzXJrgCTVuHddkdQH1PCdN95OvrRCq/vfZXLGtmDRSTQfa2E8rh2RDTdw=,iv:jGNP3oMGCEMYnlpEpCcNIvuvfgbkjk65JcDOylTMd5E=,tag:OHFbwkS++9OORoA9UZN51Q==,type:str]
    TEST_USER_EMAIL: ENC[AES256_GCM,data:pY2zwOPoGnUeS9gv4WeLNk2hupw=,iv:IJ/L8fTmCTWBUZpGvMJWBviqWyaIwEBEa1bpXJkRBfY=,tag:D/rIe7uuOobr/h3omAyOhg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:FeSihVftsjeqtF6vVj1UXMjWJGahx3V/lH4mpaIYTtawTco=,iv:B/YY4nNHCiEigSgJYmQj0ovwNeIeGgte+TNWW2Pixww=,tag:nm8aiTHnBnXGSx1sRNw2Gw==,type:str]
    RESEND_API_KEY: ENC[AES256_GCM,data:52ohCdjwTtzOCFQmpp/7dZMOW4Oq/iH0d/LCVk9a52WfvgsoJGI=,iv:zEvwugejQ9lRK4NVov78a1e80QbrM2rKakB6AnKq5k0=,tag:coFsJL3eCOuFBF878f+GRA==,type:str]
    GOOGLE_ID: ENC[AES256_GCM,data:dAY+kQ5Wc2xMbNVWU2k6EudVJxFWrN0yXKgxa9C9QA6DzRG1Fit9ZKh0dHqVOUTjx74TqUFo6vxMTBebfjgdbrRwNbDLt02G,iv:xwTA1FugINoc1WJVy5JB7wxifB1d47tLUh9dSIoa6Jo=,tag:6k8Udj1xEfaoyZFgyc1G6A==,type:str]
    GOOGLE_SECRET: ENC[AES256_GCM,data:WQtWWUzHO8VGWD29KLlFTcPQjgEsV89yh5QDfQ5Ry2mhRoU=,iv:yWr9C50ipBluh0aGX6iJqzoEyaKQe0+OFhNd+tUugNE=,tag:J16UHpt/kEnASOjuazoqrA==,type:str]
    FIRECRAWL_API_KEY: ""
    E2B_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVWlkaUFtcGl4ZVBYcHhE
            a0pnUDJ0Nk84V2ZyQUpYU2lYNVFaajdMVjBBCmF5cGk5M2F1cXNIRHBab2xWSGZK
            UWRQNFlzVlZPeFhvdVJJZ1ZKVDV5SFkKLS0tIG9MZ0YxcVE4M3NlcTVjWTEvK00x
            RVU3SXlQeFhrcGRwZlJwcnp0cCtFTFkKRiVJMVF+3F25CJjyFypCeq8GMlYyPQP/
            o7TOgS60A9h6Poa3Se+nE56ZKHOnHk60nPFcb5sk1tm+n8NtkWy7SQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cs0csgzz7xtc644my5r9ee0uy8s6zx3njnymwd32g8rwcamqzges8pds9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaS2ZqYkR1Rno4YmxROTlE
            b2hoVkY0bGJydE8ya2h5aDdxUzVPUmpGb3ljCmVzRFJxS3d2TmJleUQwNFNDY2Vr
            Q1VxUkNmYjc3ckxRem5vcXdYOTBsTnMKLS0tIGlla1ZmNTFkNGVxK0lGU1dCYjFh
            SDVLU2huUi9WaGJ1RzlYclVnVUZhdHMKwd6Floa3O3Ji4bvNqAs1XUKQT5CJKoRY
            AnYTLvyl+KXAdC/dhBi7PxqRRyT2bArrmF6RA8w0hE7e5new9PpycQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cuuzzp3fu0g62hdpgszw4ce9ndpk4zgaxaj8x3s0u00kq9xmnp6qq7547k
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T07:20:53Z"
    mac: ENC[AES256_GCM,data:AvP+1t5wNPpBhR4yG3sX81fSLi+SOBiXNTyXfmpjH9EDHQs6/aAeqxLyCRyXuXe7WdXQLvAC1gjfk9STnLevnQugBsRYeDOSU73ZXvhbneJifBVvHgBORHKMbCyMen5OvYE5GYBRJ3ageug9gVNny2rHxN0hBK5pHeYg7D25cIw=,iv:veAYMG3bdaQ0EIbOKJJdB8HUWPt3h3tZM5R8gQvntJI=,tag:k3k0rLXebkEOgEhYOiQudg==,type:str]
    version: 3.13.1
