apiVersion: v1
kind: Service

metadata:
  name: nextcrm-inngest
  namespace: ynoacamino

spec:
  selector:
    app: nextcrm-inngest
  ports:
    - name: inngest
      port: 8288
      targetPort: 8288
